const data = [
    {
      key: '1',
      placa: 'PAM 9846',
      modelo: 'GOL G5 1.0',
      fabricante: 'Wolkswagem',
      datarevisao: "2018-12-23",
      departamento: "Ciência da Computação",
      statistics: ['50,6', '2019-05-06', '175,28','6'],
    },
    {
      key: '2',
      placa: 'PAM 8272',
      modelo: 'SAVEIRO 2.0',
      fabricante: 'Wolkswagem',
      datarevisao: "2019-05-11",
      departamento: "Reitoria",
      statistics: ['15,12', '2020-01-12', '55,82', '4'],
    },
    {
      key: '3',
      placa: 'JLK 7985',
      modelo: 'FUSION 2.5',
      fabricante: 'Ford',
      datarevisao: "2019-07-06",
      departamento: "Engenharia Elétrica",
    },
    {
      key: '4',
      placa: 'PAI 4566',
      modelo: 'HB20 1.0',
      fabricante: 'Hyundai',
      datarevisao: "2019-01-16",
      departamento: "Ciência da Computação",
    },
    {
      key: '5',
      placa: 'PAZ 9826',
      modelo: 'UP 1.0',
      fabricante: 'Wolkswagem',
      datarevisao: "2019-04-17",
      departamento: "Ciência da computação",
    },
    {
      key: '6',
      placa: 'PAI 9236',
      modelo: 'POLO 2.0',
      fabricante: 'Wolkswagem',
      datarevisao: "2019-08-03",
      departamento: "Ciência da computação",
    },
    {
      key: '7',
      placa: 'JKP 9826',
      modelo: 'UP TSI 1.0',
      fabricante: 'Wolkswagem',
      datarevisao: "2019-01-15",
      departamento: "Reitoria",
    },
    {
      key: '8',
      placa: 'PAZ 2357',
      modelo: 'Fiesta 1.6',
      fabricante: 'Ford',
      datarevisao: "2019-03-20",
      departamento: "Engenharia Elétrica",
    },
    {
      key: '9',
      placa: 'JKP 2357',
      modelo: 'Ka 1.0',
      fabricante: 'Ford',
      datarevisao: "2019-02-14",
      departamento: "Reitoria",
    },
    {
      key: '10',
      placa: 'PAZ 3265',
      modelo: 'Onix 1.4',
      fabricante: 'Chevrolet',
      datarevisao: "2019-11-02",
      departamento: "Ciência da computação",
    },
    {
      key: '11',
      placa: 'PAI 5325',
      modelo: 'Celta 1.6',
      fabricante: 'Chevrolet',
      datarevisao: "2019-10-10",
      departamento: "Ciência da computação",
    }
  ];

  export default data