const data = [
    {
      key: '1',
      plate: ['PAM 9846','Operando'],
      model: 'GOL G5 1.0',
      manufacture: 'Wolkswagem',
      maintenceDate: "2018-12-23",
      departament: "Ciência da Computação",
      nextRevision: '2019-05-06', 
      statistics: {
        lastTrip: '50,6', 
        traveledWeek: '175,28',
        NumRoutesWeek: '6',
      },
    },
    {
      key: '2',
      plate: ['PAM 8272','Manuntenção'],
      model: 'SAVEIRO 2.0',
      manufacture: 'Wolkswagem',
      maintenceDate: "2019-05-11",
      departament: "Reitoria",
      statistics: {
        lastTrip: '15,12', 
        nextRevision: '2020-01-12', 
        traveledWeek: '55,82',
        NumRoutesWeek: '4',
      },
    },
    {
      key: '3',
      plate: ['JLK 7985', 'Quebrado', 'Manuntenção'],
      model: 'FUSION 2.5',
      manufacture: 'Ford',
      maintenceDate: "2019-07-06",
      departament: "Engenharia Elétrica",
    },
    {
      key: '4',
      plate: ['PAI 4566'],
      model: 'HB20 1.0',
      manufacture: 'Hyundai',
      maintenceDate: "2019-01-16",
      departament: "Ciência da Computação",
    },
    {
      key: '5',
      plate: ['PAZ 9826'],
      model: 'UP 1.0',
      manufacture: 'Wolkswagem',
      maintenceDate: "2019-04-17",
      departament: "Ciência da Computação",
    },
    {
      key: '6',
      plate: ['PAI 9236'],
      model: 'POLO 2.0',
      manufacture: 'Wolkswagem',
      maintenceDate: "2019-08-03",
      departament: "Ciência da Computação",
    },
    {
      key: '7',
      plate: ['JKP 9826'],
      model: 'UP TSI 1.0',
      manufacture: 'Wolkswagem',
      maintenceDate: "2019-01-15",
      departament: "Reitoria",
    },
    {
      key: '8',
      plate: ['PAZ 2357'],
      model: 'Fiesta 1.6',
      manufacture: 'Ford',
      maintenceDate: "2019-03-20",
      departament: "Engenharia Elétrica",
    },
    {
      key: '9',
      plate: ['JKP 2357'],
      model: 'Ka 1.0',
      manufacture: 'Ford',
      maintenceDate: "2019-02-14",
      departament: "Reitoria",
    },
    {
      key: '10',
      plate: ['PAZ 3265'],
      model: 'Onix 1.4',
      manufacture: 'Chevrolet',
      maintenceDate: "2019-11-02",
      departament: "Ciência da Computação",
    },
    {
      key: '11',
      plate: ['PAI 5325'],
      model: 'Celta 1.6',
      manufacture: 'Chevrolet',
      maintenceDate: "2019-10-10",
      departament: "Ciência da Computação",
    }
  ];

  export default data